FROM mhart/alpine-node:6.9.2

RUN apk add --no-cache make gcc g++ python git bash
COPY package.json /src/package.json


RUN apk add --update bash && rm -rf /var/cache/apk/*


WORKDIR /src
RUN npm install

ADD tmp/testrpc .

EXPOSE 8081

CMD ["/bin/bash"]

