apiVersion: v1
kind: Service
metadata:
  labels:
    app: dashboard
  name: dashboard-svc
  namespace: default
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8081
  selector:
    app: dashboard