# Group Apikeys
Welcome to the apikeys API. This API provides access to the apikeys service.

## apikeys [/apikeys]

### Create apikey [POST]

Create a new apikey

+ Request apikey (application/json; charset=utf-8)
    + Headers

            Accept: application/vnd.loomnetwork+json
    + Attributes

        + key: KEY (string)
        + account form: (account)

+ Response 201 (application/json; charset=utf-8)
    + Attributes (apikey, fixed)

### Get apikeys [GET]

Returns an apikey list.

+ Request (application/json; charset=utf-8)
    + Headers

            Accept: application/vnd.loomnetwork+json

+ Response 200 (application/json; charset=utf-8)
    + Attributes (array, fixed)
        + (apikey)

## apikey details [/apikeys/{id}]

+ Parameters
    + id: `1` (enum[string]) - The ID of the desired apikey.
        + Members
            + `1`
            + `2`
            + `3`

### Get apikey [GET]

Returns an apikey.

+ Request (application/json; charset=utf-8)
    + Headers

            Accept: application/vnd.loomnetwork+json

+ Response 200 (application/json; charset=utf-8)
    + Attributes (apikey, fixed)

### Update apikey [PUT]

Update an apikey.

+ Request apikey (application/json; charset=utf-8)
    + Headers

            Accept: application/vnd.loomnetwork+json
    + Attributes

        + key: KEY (string)
        + account form: (account)

+ Response 200 (application/json; charset=utf-8)
    + Attributes (apikey, fixed)

### Delete apikey [DELETE]

Delete an apikey.

+ Request (application/json; charset=utf-8)
    + Headers

            Accept: application/vnd.loomnetwork+json

+ Response 204

# Data Structures
## apikey (object)

+ id: *1* (number)
+ key: *KEY* (string)
+ account form: (account)
